name: CoordBook
version: 0.1.0
author: 'James Tai'
description: 'Coordinate book'
main: ca.jtai.coordbook.Main
api-version: 1.13

commands:
  coordbook:
    description: Interact with the coordinate book.
    usage: /coordbook [list|add|remove] ...
    aliases: [cb, cbook]

permissions:
  coordbook.add: { default: true }
  coordbook.pin: { default: op }
  coordbook.rename: { default: true }
  coordbook.rename.other: { default: op }
  coordbook.remove: { default: true }
  coordbook.remove.other: { default: op }
